### ISSUE TITLE
ModuleNotFoundError: No module named 'api_endpoints'

### ISSUE THREAD

**Issue by vamsitadikonda** [vamsitadikonda/slash#24]
2022-12-04T05:27:15.823426+00:00 heroku[web.1]: State changed from starting to crashed
2022-12-04T05:27:15.602375+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [4] [INFO] Starting gunicorn 20.1.0
2022-12-04T05:27:15.602670+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [4] [INFO] Listening at: http://0.0.0.0:22578 (4)
2022-12-04T05:27:15.602711+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [4] [INFO] Using worker: sync
2022-12-04T05:27:15.606135+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [9] [INFO] Booting worker with pid: 9
2022-12-04T05:27:15.608409+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [9] [ERROR] Exception in worker process
2022-12-04T05:27:15.608409+00:00 app[web.1]: Traceback (most recent call last):
2022-12-04T05:27:15.608409+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-12-04T05:27:15.608410+00:00 app[web.1]: worker.init_process()
2022-12-04T05:27:15.608410+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-12-04T05:27:15.608411+00:00 app[web.1]: self.load_wsgi()
2022-12-04T05:27:15.608411+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-12-04T05:27:15.608411+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-12-04T05:27:15.608412+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-12-04T05:27:15.608412+00:00 app[web.1]: self.callable = self.load()
2022-12-04T05:27:15.608412+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-12-04T05:27:15.608412+00:00 app[web.1]: return self.load_wsgiapp()
2022-12-04T05:27:15.608412+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-12-04T05:27:15.608412+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-12-04T05:27:15.608413+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
2022-12-04T05:27:15.608413+00:00 app[web.1]: mod = importlib.import_module(module)
2022-12-04T05:27:15.608413+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-12-04T05:27:15.608414+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-12-04T05:27:15.608414+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-12-04T05:27:15.608414+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-12-04T05:27:15.608414+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
2022-12-04T05:27:15.608414+00:00 app[web.1]: ModuleNotFoundError: No module named 'api_endpoints'
2022-12-04T05:27:15.608479+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-12-04T05:27:15.633394+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [4] [INFO] Shutting down: Master
2022-12-04T05:27:15.633419+00:00 app[web.1]: [2022-12-04 05:27:15 +0000] [4] [INFO] Reason: Worker failed to boot.

**Comment by bharathncsu** [comment]
Fixed the bug in Procfile
